# Generated by Django 3.2.4 on 2021-06-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoebox',
            options={'ordering': ['name', 'brand'], 'verbose_name': 'Shoebox', 'verbose_name_plural': 'Shoeboxes'},
        ),
        migrations.AddField(
            model_name='shoebox',
            name='brand',
            field=models.CharField(default='shoebox', max_length=100),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='description',
            field=models.CharField(default='no description', max_length=1000),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='flute_layers',
            field=models.CharField(choices=[('0.5', 'Einseitig beklebte Wellpappe'), ('1', 'Einwellige Wellpappe'), ('2', 'Zweiwellige Wellpappe'), ('3', 'Dreiwellige Wellpappe')], default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='flute_type',
            field=models.CharField(choices=[('A', 'Grobwelle'), ('B', 'Feinwelle'), ('C', 'Mittelwelle'), ('E', 'Mikrowelle'), ('F', 'Miniwelle')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoebox_images/'),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='liner_type',
            field=models.CharField(choices=[('A', 'Kraftliner'), ('B', 'Testliner'), ('C', 'Schrenzpapier'), ('U', 'Unbekannt')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='name',
            field=models.CharField(default='box-name', max_length=100),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='shoebox_pdfs/'),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='shoebox',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
