# Generated by Django 3.2.4 on 2021-07-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoebox', '0007_auto_20210712_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='box',
            new_name='comment',
        ),
    ]
