# Generated by Django 3.2.4 on 2021-07-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoebox', '0007_alter_comment_rating'),
        ('Shoebox', '0009_alter_vote_comment'),
    ]

    operations = [
    ]
