# Generated by Django 3.2.4 on 2021-07-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
        ('Shoebox', '0011_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='shoebox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shoebox.shoebox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Useradmin.myuser'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Useradmin.myuser'),
        ),
    ]
