# Generated by Django 3.2.4 on 2021-07-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shoebox', '0012_auto_20210714_2118'),
        ('Shoppingcart', '0002_alter_shoppingcartitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shoebox.shoebox'),
            preserve_default=False,
        ),
    ]
