# Generated by Django 3.2.4 on 2021-07-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingcart', '0003_auto_20210715_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product_id',
        ),
    ]
